In [42]:
from pyspark.sql import SparkSession
import pyspark.sql.types as T

In [2]:
spark= SparkSession.builder\
        .appName("Data Transformation in PySpark")\
        .master("local[*]")\
        .getOrCreate()

In [4]:
df= spark.read.format('csv').option('inferSchema', True).option('header', True)\
    .load('pathToData')

In [5]:
df.toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

### SELECT Method 1

In [6]:
df_sel= df.select('Item_Identifier', 'Item_Weight', 'Item_Fat_Content')

In [7]:
df_sel.toPandas()

     Item_Identifier  Item_Weight Item_Fat_Content
0              FDA15        9.300          Low Fat
1              DRC01        5.920          Regular
2              FDN15       17.500          Low Fat
3              FDX07       19.200          Regular
4              NCD19        8.930          Low Fat
...              ...          ...              ...
8518           FDF22        6.865          Low Fat
8519           FDS36        8.380          Regular
8520           NCJ29       10.600          Low Fat
8521           FDN46        7.210          Regular
8522           DRG01       14.800          Low Fat

[8523 rows x 3 columns]

### Method 2 using COL

In [9]:
from pyspark.sql.functions import *

In [10]:
df.select(col('Item_Identifier'), col('Item_Weight'), col('Item_Fat_Content')).toPandas()

     Item_Identifier  Item_Weight Item_Fat_Content
0              FDA15        9.300          Low Fat
1              DRC01        5.920          Regular
2              FDN15       17.500          Low Fat
3              FDX07       19.200          Regular
4              NCD19        8.930          Low Fat
...              ...          ...              ...
8518           FDF22        6.865          Low Fat
8519           FDS36        8.380          Regular
8520           NCJ29       10.600          Low Fat
8521           FDN46        7.210          Regular
8522           DRG01       14.800          Low Fat

[8523 rows x 3 columns]

## ALIAS

In [11]:
df.select(col('Item_Identifier').alias('Item ID')).toPandas()

     Item ID
0      FDA15
1      DRC01
2      FDN15
3      FDX07
4      NCD19
...      ...
8518   FDF22
8519   FDS36
8520   NCJ29
8521   FDN46
8522   DRG01

[8523 rows x 1 columns]

## FILTER/ WHERE

# We are going to:

### 1. Filter the data with fat content = regular
### 2. Slice the data with item type= Soft Drinks and Weight < 10
### 3. Fetch the data with Tier in (Tier 1 or Tier 2) and Outlet Size is Null

### Scenario 1 here

In [14]:
df.filter(col('Item_Fat_Content')=='Regular').toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
1,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
2,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
3,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
4,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
...,...,...,...,...,...,...,...,...,...,...,...,...
2884,FDN58,13.800,Regular,0.056862,Snack Foods,231.5984,OUT035,2004,Small,Tier 2,Supermarket Type1,7182.6504
2885,FDH31,12.000,Regular,0.020407,Meat,99.9042,OUT035,2004,Small,Tier 2,Supermarket Type1,595.2252
2886,FDA01,15.000,Regular,0.054489,Canned,57.5904,OUT045,2002,NaN,Tier 2,Supermarket Type1,468.7232
2887,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
2888,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976

### Scenario 2: Slice the data with item type= Soft Drinks and Weight < 10

In [17]:
df.filter(col('Item_Type')=='Soft Drinks').filter(col('Item_Weight')< 10).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
1,DRZ11,8.850,Regular,0.113124,Soft Drinks,122.5388,OUT018,2009,Medium,Tier 3,Supermarket Type2,1609.9044
2,DRF49,7.270,Low Fat,0.071078,Soft Drinks,114.2518,OUT046,1997,Small,Tier 1,Supermarket Type1,2618.5914
3,DRK12,9.500,LF,0.041878,Soft Drinks,32.9900,OUT035,2004,Small,Tier 2,Supermarket Type1,133.1600
4,DRK01,7.630,Low Fat,0.061053,Soft Drinks,95.4436,OUT035,2004,Small,Tier 2,Supermarket Type1,1418.1540
...,...,...,...,...,...,...,...,...,...,...,...,...
161,DRE48,8.430,Low Fat,0.017396,Soft Drinks,196.0768,OUT018,2009,Medium,Tier 3,Supermarket Type2,4138.6128
162,DRA59,8.270,Regular,0.214125,Soft Drinks,183.9924,OUT010,1998,NaN,Tier 3,Grocery Store,185.0924
163,DRZ11,8.850,Regular,0.112893,Soft Drinks,123.3388,OUT045,2002,NaN,Tier 2,Supermarket Type1,2972.1312
164,DRJ49,6.865,Low Fat,0.014072,Soft Drinks,127.3652,OUT017,2007,NaN,Tier 2,Supermarket Type1,1679.1476
165,DRJ49,6.865,Low Fat,0.000000,Soft Drinks,129.9652,OUT013,1987,High,Tier 3,Supermarket Type1,2324.9736

### or even better one using AND Operator (&) in PySpark

In [23]:
df.filter((col('Item_Type')=='Soft Drinks') & (col('Item_Weight')<10)).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
1,DRZ11,8.850,Regular,0.113124,Soft Drinks,122.5388,OUT018,2009,Medium,Tier 3,Supermarket Type2,1609.9044
2,DRF49,7.270,Low Fat,0.071078,Soft Drinks,114.2518,OUT046,1997,Small,Tier 1,Supermarket Type1,2618.5914
3,DRK12,9.500,LF,0.041878,Soft Drinks,32.9900,OUT035,2004,Small,Tier 2,Supermarket Type1,133.1600
4,DRK01,7.630,Low Fat,0.061053,Soft Drinks,95.4436,OUT035,2004,Small,Tier 2,Supermarket Type1,1418.1540
...,...,...,...,...,...,...,...,...,...,...,...,...
161,DRE48,8.430,Low Fat,0.017396,Soft Drinks,196.0768,OUT018,2009,Medium,Tier 3,Supermarket Type2,4138.6128
162,DRA59,8.270,Regular,0.214125,Soft Drinks,183.9924,OUT010,1998,NaN,Tier 3,Grocery Store,185.0924
163,DRZ11,8.850,Regular,0.112893,Soft Drinks,123.3388,OUT045,2002,NaN,Tier 2,Supermarket Type1,2972.1312
164,DRJ49,6.865,Low Fat,0.014072,Soft Drinks,127.3652,OUT017,2007,NaN,Tier 2,Supermarket Type1,1679.1476
165,DRJ49,6.865,Low Fat,0.000000,Soft Drinks,129.9652,OUT013,1987,High,Tier 3,Supermarket Type1,2324.9736

### Scenario 3: Fetch the data with Tier in (either Tier 1 or Tier 2) and Outlet Size is Null

In [29]:
df.filter(col('Outlet_Size').isNull() & (col('Outlet_Location_Type').isin('Tier 1', 'Tier 2'))).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDH17,16.20,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,None,Tier 2,Supermarket Type1,1076.5986
1,FDU28,19.20,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,None,Tier 2,Supermarket Type1,4710.5350
2,NCD06,13.00,Low Fat,0.099887,Household,45.9060,OUT017,2007,None,Tier 2,Supermarket Type1,838.9080
3,FDO23,17.85,Low Fat,0.000000,Breads,93.1436,OUT045,2002,None,Tier 2,Supermarket Type1,2174.5028
4,NCP05,19.60,Low Fat,0.000000,Health and Hygiene,153.3024,OUT045,2002,None,Tier 2,Supermarket Type1,2428.8384
...,...,...,...,...,...,...,...,...,...,...,...,...
1850,FDW21,5.34,Regular,0.005998,Snack Foods,100.4358,OUT017,2007,None,Tier 2,Supermarket Type1,1508.0370
1851,NCH43,8.42,Low Fat,0.070712,Household,216.4192,OUT045,2002,None,Tier 2,Supermarket Type1,3020.0688
1852,FDW31,11.35,Regular,0.043246,Fruits and Vegetables,199.4742,OUT045,2002,None,Tier 2,Supermarket Type1,2587.9646
1853,FDA01,15.00,Regular,0.054489,Canned,57.5904,OUT045,2002,None,Tier 2,Supermarket Type1,468.7232
1854,FDS36,8.38,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,None,Tier 2,Supermarket Type1,549.2850

## withColumnRenamed

### changing the name of the column 'Item Weight' to 'Item Wt.'

In [31]:
df.withColumnRenamed('Item_weight', 'Item Wt.').toPandas()

,Item_Identifier,Item Wt.,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

## withColumn

In [32]:
df= df.withColumn('flag', lit("new"))

In [33]:
df.toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,new
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,new
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,new
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,new
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,new

df.withColumn('Multiply', col('Item_Weight')*col('Item_MRP')).toPandas()

### Change the content of Item_Fat_Content onto their short forms like LF, R, ...

In [36]:
df.withColumn('Item_Fat_Content', regexp_replace(col('Item_Fat_Content'), "Regular", "R"))\
    .withColumn('Item_Fat_Content', regexp_replace(col('Item_Fat_Content'), "Low Fat", "LF")).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDA15,9.300,LF,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
1,DRC01,5.920,R,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
2,FDN15,17.500,LF,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
3,FDX07,19.200,R,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
4,NCD19,8.930,LF,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,LF,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,new
8519,FDS36,8.380,R,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,new
8520,NCJ29,10.600,LF,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,new
8521,FDN46,7.210,R,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,new
8522,DRG01,14.800,LF,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,new

# Type Casting

In [43]:
df= df.withColumn('Item_Weight', col('Item_Weight').cast(T.StringType()))

In [44]:
df.toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDA15,9.3,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
2,FDN15,17.5,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
3,FDX07,19.2,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,new
8519,FDS36,8.38,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,new
8520,NCJ29,10.6,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,new
8521,FDN46,7.21,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,new
8522,DRG01,14.8,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,new

In [45]:
df.printSchema()

root
 |-- Item_Identifier: string (nullable = true)
 |-- Item_Weight: string (nullable = true)
 |-- Item_Fat_Content: string (nullable = true)
 |-- Item_Visibility: double (nullable = true)
 |-- Item_Type: string (nullable = true)
 |-- Item_MRP: double (nullable = true)
 |-- Outlet_Identifier: string (nullable = true)
 |-- Outlet_Establishment_Year: integer (nullable = true)
 |-- Outlet_Size: string (nullable = true)
 |-- Outlet_Location_Type: string (nullable = true)
 |-- Outlet_Type: string (nullable = true)
 |-- Item_Outlet_Sales: double (nullable = true)
 |-- flag: string (nullable = false)

# Sort/ Order By

### Sorting our data from highest to lowest Item weight

In [46]:
df.sort(col('Item_weight').desc()).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDR13,9.895,Regular,0.028697,Canned,117.0492,OUT013,1987,High,Tier 3,Supermarket Type1,810.9444,new
1,DRD49,9.895,Low Fat,0.167799,Soft Drinks,239.4564,OUT035,2004,Small,Tier 2,Supermarket Type1,5243.8408,new
2,FDR13,9.895,Regular,0.028838,Canned,117.8492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1506.0396,new
3,FDT16,9.895,Regular,0.048761,Frozen Foods,260.5278,OUT045,2002,NaN,Tier 2,Supermarket Type1,8851.1452,new
4,DRD49,9.895,Low Fat,0.168780,Soft Drinks,236.8564,OUT017,2007,NaN,Tier 2,Supermarket Type1,4767.1280,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,DRK37,NaN,Low Fat,0.043792,Soft Drinks,189.0530,OUT027,1985,Medium,Tier 3,Supermarket Type3,6261.8490,new
8519,DRG13,NaN,Low Fat,0.037006,Soft Drinks,164.7526,OUT027,1985,Medium,Tier 3,Supermarket Type3,4111.3150,new
8520,NCN14,NaN,Low Fat,0.091473,Others,184.6608,OUT027,1985,Medium,Tier 3,Supermarket Type3,2756.4120,new
8521,FDU44,NaN,Regular,0.102296,Fruits and Vegetables,162.3552,OUT019,1985,Small,Tier 1,Grocery Store,487.3656,new
8522,NCN18,NaN,Low Fat,0.124111,Household,111.7544,OUT027,1985,Medium,Tier 3,Supermarket Type3,4138.6128,new

In [48]:
df.sort(col('Item_Visibility').asc()).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDX07,19.2,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
1,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
2,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088,new
3,FDY07,11.8,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266,new
4,FDP33,18.7,Low Fat,0.000000,Snack Foods,256.6672,OUT018,2009,Medium,Tier 3,Supermarket Type2,3068.0064,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,NCE31,7.67,Low Fat,0.309390,Household,33.2216,OUT010,1998,NaN,Tier 3,Grocery Store,138.4864,new
8519,FDT24,12.35,Regular,0.311090,Baking Goods,79.2328,OUT010,1998,NaN,Tier 3,Grocery Store,154.4656,new
8520,FDJ56,NaN,Low Fat,0.321115,Fruits and Vegetables,100.7700,OUT019,1985,Small,Tier 1,Grocery Store,199.7400,new
8521,NCZ18,NaN,Low Fat,0.325781,Household,252.7698,OUT019,1985,Small,Tier 1,Grocery Store,761.0094,new
8522,FDU13,NaN,low fat,0.328391,Canned,146.0418,OUT019,1985,Small,Tier 1,Grocery Store,588.5672,new

### Sorting based on multiple columns

In [49]:
df.sort(['Item_Weight', 'Item_Visibility'], ascending=[0, 0]).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,DRD49,9.895,Low Fat,0.168780,Soft Drinks,236.8564,OUT017,2007,NaN,Tier 2,Supermarket Type1,4767.1280,new
1,DRD49,9.895,Low Fat,0.168171,Soft Drinks,237.7564,OUT045,2002,NaN,Tier 2,Supermarket Type1,3813.7024,new
2,DRD49,9.895,LF,0.167831,Soft Drinks,237.4564,OUT046,1997,Small,Tier 1,Supermarket Type1,715.0692,new
3,DRD49,9.895,Low Fat,0.167799,Soft Drinks,239.4564,OUT035,2004,Small,Tier 2,Supermarket Type1,5243.8408,new
4,NCJ54,9.895,Low Fat,0.060189,Household,233.0642,OUT045,2002,NaN,Tier 2,Supermarket Type1,6041.4692,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDT24,NaN,Regular,0.000000,Baking Goods,75.9328,OUT027,1985,Medium,Tier 3,Supermarket Type3,3012.0792,new
8519,FDX31,NaN,Regular,0.000000,Fruits and Vegetables,234.7958,OUT019,1985,Small,Tier 1,Grocery Store,467.3916,new
8520,DRH39,NaN,low fat,0.000000,Dairy,75.9670,OUT019,1985,Small,Tier 1,Grocery Store,153.1340,new
8521,FDT48,NaN,Low Fat,0.000000,Baking Goods,196.5084,OUT027,1985,Medium,Tier 3,Supermarket Type3,793.6336,new
8522,FDQ58,NaN,Low Fat,0.000000,Snack Foods,154.5340,OUT019,1985,Small,Tier 1,Grocery Store,459.4020,new

### Sorting by ascending order in one column and by descending order in another column

In [52]:
df.sort(['Item_Weight', 'Item_Visibility'], ascending=[0, 1]).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDR13,9.895,Regular,0.028697,Canned,117.0492,OUT013,1987,High,Tier 3,Supermarket Type1,810.9444,new
1,FDR13,9.895,Regular,0.028765,Canned,115.3492,OUT049,1999,Medium,Tier 1,Supermarket Type1,1274.3412,new
2,FDR13,9.895,Regular,0.028838,Canned,117.8492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1506.0396,new
3,FDT16,9.895,Regular,0.048662,Frozen Foods,261.7278,OUT046,1997,Small,Tier 1,Supermarket Type1,4685.9004,new
4,FDT16,9.895,Regular,0.048738,Frozen Foods,262.1278,OUT049,1999,Medium,Tier 1,Supermarket Type1,3904.9170,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,DRF01,NaN,Low Fat,0.306543,Soft Drinks,147.3102,OUT019,1985,Small,Tier 1,Grocery Store,291.6204,new
8519,FDG32,NaN,Low Fat,0.308145,Fruits and Vegetables,222.0772,OUT019,1985,Small,Tier 1,Grocery Store,889.5088,new
8520,FDJ56,NaN,Low Fat,0.321115,Fruits and Vegetables,100.7700,OUT019,1985,Small,Tier 1,Grocery Store,199.7400,new
8521,NCZ18,NaN,Low Fat,0.325781,Household,252.7698,OUT019,1985,Small,Tier 1,Grocery Store,761.0094,new
8522,FDU13,NaN,low fat,0.328391,Canned,146.0418,OUT019,1985,Small,Tier 1,Grocery Store,588.5672,new

# Limit

In [53]:
df.limit(10).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDA15,9.3,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
2,FDN15,17.5,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
3,FDX07,19.2,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088,new
6,FDO10,13.65,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528,new
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636,new
8,FDH17,16.2,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986,new
9,FDU28,19.2,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350,new

# DROP

In [54]:
df.drop('Item_Visibility').toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDA15,9.3,Low Fat,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
1,DRC01,5.92,Regular,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
2,FDN15,17.5,Low Fat,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
3,FDX07,19.2,Regular,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
4,NCD19,8.93,Low Fat,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,new
8519,FDS36,8.38,Regular,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,new
8520,NCJ29,10.6,Low Fat,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,new
8521,FDN46,7.21,Regular,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,new
8522,DRG01,14.8,Low Fat,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,new

### Dropping Multiple Columns

In [55]:
df.drop('Item_Visibility', 'Item_Type').toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDA15,9.3,Low Fat,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
1,DRC01,5.92,Regular,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
2,FDN15,17.5,Low Fat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
3,FDX07,19.2,Regular,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
4,NCD19,8.93,Low Fat,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,new
8519,FDS36,8.38,Regular,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,new
8520,NCJ29,10.6,Low Fat,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,new
8521,FDN46,7.21,Regular,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,new
8522,DRG01,14.8,Low Fat,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,new

# Drop Duplicates

In [56]:
df.dropDuplicates().toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDX20,7.365,Low Fat,0.042560,Fruits and Vegetables,226.1720,OUT046,1997,Small,Tier 1,Supermarket Type1,3169.2080,new
1,FDH28,15.85,Regular,0.110031,Frozen Foods,37.2506,OUT046,1997,Small,Tier 1,Supermarket Type1,265.6542,new
2,NCL18,18.85,Low Fat,0.167444,Household,194.6136,OUT013,1987,High,Tier 3,Supermarket Type1,1166.4816,new
3,FDG45,8.1,Low Fat,0.000000,Fruits and Vegetables,211.8902,OUT018,2009,Medium,Tier 3,Supermarket Type2,3823.0236,new
4,FDT34,9.3,Low Fat,0.174621,Snack Foods,104.2964,OUT049,1999,Medium,Tier 1,Supermarket Type1,1998.7316,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDP03,5.15,Regular,0.061301,Meat,122.1388,OUT045,2002,NaN,Tier 2,Supermarket Type1,2352.9372,new
8519,FDW26,11.8,Regular,0.179192,Dairy,224.2772,OUT010,1998,NaN,Tier 3,Grocery Store,667.1316,new
8520,FDX45,NaN,Low Fat,0.104348,Snack Foods,156.2630,OUT027,1985,Medium,Tier 3,Supermarket Type3,4850.3530,new
8521,NCT53,5.4,Low Fat,0.048388,Health and Hygiene,163.0526,OUT017,2007,NaN,Tier 2,Supermarket Type1,2302.3364,new
8522,FDS36,8.38,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,new

### Dropping duplicates based on a particular column only

In [57]:
df.drop_duplicates(subset= ['Item_Type']).toPandas()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,flag
0,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088,new
1,FDO23,17.85,Low Fat,0.000000,Breads,93.1436,OUT045,2002,NaN,Tier 2,Supermarket Type1,2174.5028,new
2,FDP49,9.0,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192,new
3,FDC14,NaN,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362,new
4,FDA15,9.3,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,new
5,FDH17,16.2,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986,new
6,FDX07,19.2,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,new
7,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680,new
8,NCB42,11.8,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888,new
9,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,new
10,FDN15,17.5,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,new
11,NCN07,18.5,Low Fat,0.056816,Others,132.1284,OUT010,1998,NaN,Tier 3,Grocery Store,263.6568,new
12,FDG33,NaN,Regular,0.139561,Seafood,170.4764,OUT027,1985,Medium,Tier 3,Supermarket Type3,3435.5280,new
13,FDO10,13.65,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528,new
14,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,new
15,FDH35,18.25,Low Fat,0.000000,Starchy Foods,164.7526,OUT045,2002,NaN,Tier 2,Supermarket Type1,4604.6728,new